name: thoughtboard CI
on: 
  push: 
    branches: [ main, feature/ci_flow ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'


jobs:
  # ----------------------------------
  build:                                    # builds the application for CI env
    runs-on: [ubuntu-latest]
    env:
      MONGO_URI: mongodb://localhost/thoughtboard
      PORT: 5000
      GOOGLE_ID: process.env.GOOGLE_ID
      GOOGLE_SECRET: process.env.GOOGLE_SECRET
      GITHUB_ID: process.env.GITHUB_ID
      GITHUB_SECRET: process.env.GITHUB_SECRET
      FACEBOOK_ID: process.env.FACEBOOK_ID
      FACEBOOK_SECRET: process.env.FACEBOOK_SECRET
      LINKEDIN_ID: process.env.LINKEDIN_ID
      LINKEDIN_SECRET: process.env.LINKEDIN_SECRET
      
    strategy:
      matrix:
        #os: [ubuntu-latest]  #, windows-latest, macos-latest]
        node-version: [18] # [16, 18]
        mongodb-version: ['5.0'] #, '6.0']
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2           # fetches and checks out the repo
      
      - name: Setup Node.js environment ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}

      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      
      - run: npm install                    # defines terminal commands to run
      - run: npm run ci-test
        shell: bash